### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by Si-Chong** [aravind-j/viabilitymetrics#1]
Dear Authors,

I am quite excited to find this package, which seems to have the functions I have been seeking after. Thank you for developing it.
However, I cannot install it.
I am using R version 3.6.3, and followed the install instruction:
devtools::install_github("aravind-j/viabilitymetrics")

I got the following error message:
Error: Failed to install 'viabilitymetrics' from GitHub:
  System command 'Rcmd.exe' failed, exit status: 1, stdout + stderr (last 10 lines):
E> ** inst
E> ** byte-compile and prepare package for lazy loading
E> Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
E>   there is no package called 'minpack.lm'
E> Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
E> Execution halted
E> ERROR: lazy loading failed for package 'viabilitymetrics'
E> * removing 'C:/Users/sch10wk/AppData/Local/Temp/RtmpWkQNJK/Rinst873c5aa6197d/viabilitymetrics'
E>       -----------------------------------
E> ERROR: package installation failed

Appreciate you could help. Thank you!

**Comment by aravind-j** [comment]
I suspect you are using windows and this seems to be an issue with R not being detect `Rtools`. You need it for installing packages from source in windows.

check if you have it using the `has_rtools()` function from `pkgbuild`.
`pkgbuild::has_rtools()`

Also check if `Rtools `is included in path.
`Sys.getenv('PATH')`

**Comment by Si-Chong** [comment]
Thank you for reply.
I got these messages, which seem all right:
> pkgbuild::has_rtools()
[1] TRUE
> Sys.getenv('PATH')
[1] "C:\\Users\\sch10wk\\Documents\\R\\R-3.6.3\\bin\\x64;C:\\Program Files\\ImageMagick-7.0.10-Q16;C:\\ProgramData\\Oracle\\Java\\javapath;C:\\Windows\\System32;C:\\Windows;C:\\Windows\\System32\\wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files (x86)\\Skype\\Phone\\;C:\\sybase\\OCS-12_0\\dll;C:\\sybase\\OCS-12_0\\bin;X:\\apps\\CRIS\\PWRS32\\pb5i32dk;C:\\Program Files\\PuTTY\\;C:\\Users\\sch10wk\\AppData\\Local\\Microsoft\\WindowsApps"

Any other ideas?
I am using the most updated version of R (3.6.3) -- could it be due to this?

**Comment by aravind-j** [comment]
It seems you have Rtools installed, but it is not added to the windows PATH. You need this to install any source package.

You need to add the file path to Rtools in the environment variables in windows.
You need to have something like "C:\Rtools\\bin", "C:\Rtools\mingw_64\bin" and "C:\Rtools\mingw_32\bin" in the path. Check this link for more details.

https://community.rstudio.com/t/how-to-install-rtools-without-edit-path-to-build-from-source/9502/4
